
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run fast tests (exclude slow tests)
	pytest -k "not slow" -v

test-full: ## Run all tests
	pytest -v

test-cov: ## Run tests with coverage
	pytest --cov=src --cov-report=html --cov-report=term

test-data: ## Test datamodules only
	pytest tests/test_isic_datamodule.py tests/test_datamodules.py -v

test-model: ## Test model only
	pytest tests/test_model.py -v

test-config: ## Test configurations
	pytest tests/test_configs.py -v

test-spatial: ## Test spatial encoding
	pytest tests/test_spatial_encoding.py -v

train: ## Train the model
	python src/train.py

eval: ## Evaluate the model
	python src/eval.py
